### PR TITLE
Azure AD B2C Custom Domains

### PR DESCRIPTION
**Pull request by kurucu**
Azure AD B2C allows for [Custom Domains](https://learn.microsoft.com/en-us/azure/active-directory-b2c/b2clogin#change-identity-provider-redirect-urls), as well as use of b2clogin.com, as the former isolates your cookies and user authentication.

As such, the possible URLs we need to support are as follows:

- https://{your-tenant-name}.b2clogin.com/{your-tenant-id}/oauth2/authresp
- https://{your-tenant-name}.b2clogin.com/{your-tenant-name}.onmicrosoft.com/oauth2/authresp
- https://{your-custom-domain}/{your-tenant-id}/oauth2/authresp
- https://{your-custom-domain}/{your-tenant-name}.onmicrosoft.com/oauth2/authresp

### CODE REVIEW

**Comment by kurucu** [comment]
This is ready for review now.

**Comment by atymic** [comment]
@fujie
@lsmith77

Any thoughts on this one?

**Comment by lsmith77** [comment]
I do not have a setup to test this, but it is correct that there is a possibility for custom domains.

**Comment by fujie** [comment]
no objection from me. It seems like that the custom domain url patterns are correct.

**Pull request merged**
