### PR TITLE
Update default scopes (see SocialiteProviders/Microsoft-Graph#1)

### PR DESCRIPTION
**Pull request by markspolakovs**
Update default scopes (see SocialiteProviders/Microsoft-Graph#1)

### CODE REVIEW

**Comment by faustbrian** [comment]
Did you test if the full login is working and the user object contains all data?

**Comment by markspolakovs** [comment]
@faustbrian It does appear to contain all the data it is supposed to (from the `User.Read` scope).

**Comment by faustbrian** [comment]
I will update the graph repository and tag a new release when I am back at my macbook tomorrow.

**Comment by faustbrian** [comment]
Tagged a new release for the graph provider.

**Pull request merged**
