### PR TITLE
Check if no dropbox avatar exists

### PR DESCRIPTION
**Pull request by iemand002**
Forgot to check what it does if there is no avatar => $user['profile_photo_url'] does not exist so check if isset

### CODE REVIEW

**Comment by faustbrian** [comment]
Please use array_get for this check.

**Comment by iemand002** [comment]
Never used that before, learned something new today

**Comment by faustbrian** [comment]
You can omit the `, null` at the end, array_get returns null by default.

**Comment by iemand002** [comment]
Finally 😄

**Pull request merged**
