### PR TITLE
No need to set the grant_type field again

### PR DESCRIPTION
**Pull request by lucasmichot**
No need to set the `grant_type` field again, it is already set with the value `authorization_code` in the parent method.

---

Requires https://github.com/SocialiteProviders/Providers/pull/899

### CODE REVIEW

**Review by atymic — CHANGES_REQUESTED** [review]
https://github.com/SocialiteProviders/Manager/blob/master/composer.json#L35

This allows v4 or v5, meaning if the user has v4, which doesn't have the grant type won't the provider break?
I guess to merge this we'd need to bump the min to v5 on manager?

**Comment by atymic** [comment]
ping @lucasmichot

**Comment by atymic** [comment]
ping @lucasmichot

**Comment by lucasmichot** [comment]
> This allows v4 or v5, meaning if the user has v4, which doesn't have the grant type won't the provider break?
> I guess to merge this we'd need to bump the min to v5 on manager?

Sorry for the late reply. Yes indeed, we need to bump in the Manager package at some point

**Comment by atymic** [comment]
v4 is two years old, and we'd only lose support for laravel 5.7/5.8
Happy to bump to v5 min then we can merge this?

https://github.com/laravel/socialite/releases/tag/v5.0.0

**Comment by lucasmichot** [comment]
> v4 is two years old, and we'd only lose support for laravel 5.7/5.8 Happy to bump to v5 min then we can merge this?
> 
> https://github.com/laravel/socialite/releases/tag/v5.0.0

Totally fine with losing support for these versions 👍

**Comment by atymic** [comment]
Tagged as v4.2, i guess you'll have to enforce a min version for every package here?
https://github.com/SocialiteProviders/Manager/releases/tag/v4.2.0

**Comment by lucasmichot** [comment]
Thanks @atymic , see https://github.com/SocialiteProviders/Providers/pull/899

**Pull request closed without merging**
