### PR TITLE
Bump to PHP 8.1

### PR DESCRIPTION
**Pull request by lucasmichot**
This PR bumps the minimum version requirement to PHP 8.1
As PHP 8.0 will be EOL in a few months.

Cf. https://www.php.net/supported-versions.php

---

The GA PHP versions are updated accordingly.

### CODE REVIEW

**Comment by atymic** [comment]
TBH i'm not a fan of removing supported versions just because they are EOL. AFAIK there's nothing we need that's not available in `8.0`, and despite it being EOL it's still used (has a 10% share)
https://packagist.org/php-statistics

**Comment by lucasmichot** [comment]
@atymic Should we keep on supporting PHP versions 7.* then?

**Comment by atymic** [comment]
AFAIK we dropped 7.x support? Maybe revisit once 8.0 is EOL?

**Comment by lucasmichot** [comment]
> AFAIK we dropped 7.x support? Maybe revisit once 8.0 is EOL?

The support is actually not totally dropped, I have created https://github.com/SocialiteProviders/Providers/pull/1060 for that

Let's revisit this PR later

**Pull request closed without merging**
