### PR TITLE
Steam Provider - always use http #562

### PR DESCRIPTION
**Pull request by michaloravec**
More info is in this issue #562

### CODE REVIEW

**Review by FoksVHox — APPROVED** [review]
Seems fine to me

**Comment by atymic** [comment]
Can you check what redirect URLs your server is generating?
I checked and HTTPs is supported by them (and much more secure). There must be a different issue in our implementation

**Comment by michaloravec** [comment]
@atymic This provider is based on this package https://github.com/invisnik/laravel-steam-auth

And they also use `http`, except **OPENID_URL** which is through `https` https://github.com/invisnik/laravel-steam-auth/blob/master/src/SteamAuth.php#L49

And I don't change **OPENID_URL** in this pull request https://github.com/SocialiteProviders/Providers/blob/master/src/Steam/Provider.php#L36 it's still on `https`

**Review by atymic — APPROVED** [review]

**Comment by atymic** [comment]
Thanks!

**Pull request merged**
