### PR TITLE
add AmoCRM provider

### PR DESCRIPTION
**Pull request by mityukov**
Hi, can I add one?

amoCRM: https://www.amocrm.com/
OAuth documentation: https://www.amocrm.com/developers/content/oauth/step-by-step/

### CODE REVIEW

**Review by lucasmichot — CHANGES_REQUESTED** [review]
thanks for your contribution,
Can you double check the doc ?
https://www.amocrm.com/developers/content/oauth/step-by-step/

It seems that there is a confusion between domain and subdomain
Also I don't see any mention in the doc of different TLDs ( ru or com) ?

**Comment by mityukov** [comment]
@lucasmichot amoCRM is a multitenancy app. It expects the first request (to get code) to be sent to `www.amocrm.(com|ru)`, but the next requests (to get the access token and all the further) should be sent to appropriate subdomain (like clientname.amocrm.(com|ru)) and we get that subdomain from the 'referer' param).

> Also I don't see any mention in the doc of different TLDs ( ru or com) ?

They have it separated for some reason. The docs at https://www.amocrm.com/developers/ only mention amocrm.com, and the docs at https://www.amocrm.ru/developers/ — only mention amocrm.ru

**Comment by mityukov** [comment]
@lucasmichot 
> What do you think ?

Looks good to me. Do I need to pull this in and resubmit or anything? This is my first pull request on github 🤗

**Comment by lucasmichot** [comment]
> This is my first pull request on github

👏 🎉  Thanks for that 🙏 

Nah all good, no need to resubmit anything, I will fix the linter and approve it

**Review by lucasmichot — APPROVED** [review]

**Comment by mityukov** [comment]
@lucasmichot tested it with your changes — seems to work like a charm!

Note: right now, requires the following section in `composer.json`:
```json
    "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:mityukov/amocrm-socialize"
        }
    ],
```

**Review by atymic — APPROVED** [review]

**Review by atymic — APPROVED** [review]

**Comment by mityukov** [comment]
Thanks! May I suggest "Productivity / Business" category for this integration? (I mean the left menu of the socialite providers site)

**Pull request merged**
