### PR TITLE
Create a provider for Sign In with Apple

### PR DESCRIPTION
**Pull request by pxgamer**
This starts to add `Sign In with Apple` support, and is based off of [Aaron Parecki's blog on Okta](https://developer.okta.com/blog/2019/06/04/what-the-heck-is-sign-in-with-apple).

I haven't been able to add the `getUserByToken` or `mapUserToObject` methods yet unfortunately as I can't find an API endpoint for this. 🤔

I thought it may be worth adding this PR and if anyone finds an endpoint for user data, this can be updated.

If it's better to just close this because of the lack of those methods, feel free to do so.

### CODE REVIEW

**Comment by driesvints** [comment]
@pxgamer we're considering adding this provider to the main socialite library so feel free to send in this pr there: https://github.com/laravel/socialite/issues/369

**Comment by pxgamer** [comment]
@driesvints, will do! That sounds great.

**Comment by theodh** [comment]
The email address will be available soon, see issue: 
https://forums.developer.apple.com/thread/118209

**Comment by alinmiron** [comment]
Hello, any progress with this? Thanks

**Comment by pxgamer** [comment]
Hi @alinmiron, doesn't look like it for now. It's more likely to be added to the official Socialite package (https://github.com/laravel/socialite/issues/369) and I don't have an Apple developer account, so I'm unable to really test this.

**Comment by mikebronner** [comment]
I went ahead and wrote a package for this, complete with the entire setup process with the Apple Developer account. Didn't mean to detract from this effort, but it appears to have stalled, and I wanted to move forward.

Would love to hear your feedback. Thanks!

https://github.com/GeneaLabs/laravel-sign-in-with-apple

**Comment by pxgamer** [comment]
If you'd like, I can close this PR and let you open a new one with your changes?

The progress for this has indeed stalled as I am unable to test any changes due to not having an Apple Developer subscription, so that may be best. :+1:

**Comment by mikebronner** [comment]
@pxgamer I currently don't plan on submitting it to this repo, as it contains additional functionality that this repo doesn't support. Is that an issue?

**Comment by pxgamer** [comment]
No problem. :+1: I might leave this here for now then, and anyone else can pick it up if they want. :slightly_smiling:

**Comment by jmarcher** [comment]
What is the status on this?

**Comment by m1guelpf** [comment]
@pxgamer Is this PR ready for review?

**Comment by pxgamer** [comment]
@m1guelpf, I think I'm going to close this, and direct people to [the package](https://github.com/GeneaLabs/laravel-sign-in-with-apple) by @mikebronner. 👍

**Comment by vonec** [comment]
@owenvoke we are interested in taking this up, can you guide us on how we can submit the PR and the standards we need to follow

**Comment by owenvoke** [comment]
@vonec, I don't think that this is really possible with the way that Socialite works without using custom code such as in the [previously-mentioned package](https://github.com/GeneaLabs/laravel-sign-in-with-apple). 👍 This is partly due to how Socialite is designed (for proper OAuth providers), and partly because of Apple not following the standard as far as I can tell.

However, I am probably not the best person to ask as I do not have an Apple developer account or experience with the Apple API.

**Comment by vonec** [comment]
@owenvoke Thank you for the brisk reply, the issue with the custom code ( ruby to generate the CLIENT SECRET) was resolved. Apple does follow the standard but the data is encoded in a jwt token, we have finished writing the package which does both client secret generation, and jwt signature validation without any external custom code. https://github.com/Ahilmurugesan/socialite-apple

**Comment by owenvoke** [comment]
I am not a member of the Socialite team, so as mentioned I'm not the best person to ask.

However, you should be able to fork this repository, create a directory for `src/Apple`, and then copy the files you've created to that directory:
- https://github.com/Ahilmurugesan/socialite-apple/blob/master/src/AppleExtendSocialite.php
- https://github.com/Ahilmurugesan/socialite-apple/blob/master/src/Provider.php
- https://github.com/Ahilmurugesan/socialite-apple/blob/master/src/composer.json

---

The Composer JSON should probably match the existing providers, so:

<details>

```json
{
    "name": "socialiteproviders/apple",
    "description": "Apple OAuth2 Provider for Laravel Socialite",
    "license": "MIT",
    "require": {
        "php": ">=5.5.9",
        "socialiteproviders/manager": "^2.0|^3.0"
    },
    "autoload": {
        "psr-4": {
            "SocialiteProviders\\Apple\\": ""
        }
    }
}
```
</details>

The `AppleExtendSocialite` class looks fine, but should be using the `SocialiteProviders\Apple` namespace.

And the `Provider` class, I think it should be using `$this->request` instead of the helper method for consistency with the other providers.

---

Once you've opened a pull request, I'm happy to take a look and I'm sure the maintainers will take a look as well. 👍

**Comment by Ahilmurugesan** [comment]
Added a pull request for the Sign in with Apple socialite provider with following the socialite manager specifications and code styles from the contribute section. 

https://github.com/SocialiteProviders/Providers/pull/405 

Thank You for guiding us and looking forward to getting this merged.

**Pull request closed without merging**
