### PR TITLE
Add Laravel Passport to split.sh

### PR DESCRIPTION
**Pull request by recca0120**
Add Laravel Passport to split.sh

### CODE REVIEW

**Comment by recca0120** [comment]
Hi @faustbrian 
I could't find socialiteproviders/laravelpassport in packagist.org
what can I do for this issue ??

**Comment by faustbrian** [comment]
Currently running the split.sh, should be available in roughly 30 minutes on packagist.

**Comment by recca0120** [comment]
OK thanks

**Comment by faustbrian** [comment]
https://packagist.org/packages/socialiteproviders/laravelpassport

**Pull request merged**
