### PR TITLE
Enable PKCE for Discord

### PR DESCRIPTION
**Pull request by ferrari308guy**

### CODE REVIEW

**Comment by atymic** [comment]
I had a look at the docs and didn't see any mention of PKCE
https://discord.com/developers/docs/topics/oauth2

Can you link the docs please?

**Comment by ferrari308guy** [comment]
> I had a look at the docs and didn't see any mention of PKCE https://discord.com/developers/docs/topics/oauth2
> 
> Can you link the docs please?

Yes, I couldn't find any mention of PKCE in the docs, either.

I tried to implement the Discord package as-is via Laravel Socialite. When trying to access the user property on the callback function via the following:

`$user = Socialite::driver('discord')->user();`

I received a 400 error from the server with the message that I was missing a `code_verifier` parameter. I did some digging and it appears this parameter is tied to PKCE, which led me to conclude that PKCE needs to be enabled for Discord. After enabling PKCE via the change I propose in this PR, I was able to access the user parameter without issue.

**Comment by atymic** [comment]
See this, seems it could be something else @ferrari308guy 
https://github.com/SocialiteProviders/Providers/issues/835?

**Comment by ferrari308guy** [comment]
I made a comment in #835. I had a configuration issue on my end that was the source of the problem. I'll close this PR.

**Pull request closed without merging**
