### PR TITLE
Added Discogs provider

### PR DESCRIPTION
**Pull request by bbeng89**
Added an OAuth1 provider for discogs.com.

### CODE REVIEW

**Comment by faustbrian** [comment]
Has to be added to https://github.com/SocialiteProviders/Providers/blob/master/build/split.sh and all new providers should be for PHP 7 and Manager 3.0.

**Comment by bbeng89** [comment]
Ah, i'm sorry, I didn't know about those requirements. Alright, I'll submit another PR.

**Comment by bbeng89** [comment]
I'm new to contributing on github, so if it seems like I have no idea what i'm doing that's because I don't lol. Anyway, I just realized I don't need to make another PR, the changes showed up here when I pushed. Sorry for the confusion! Please just let me know if I'm doing anything wrong, or if I need to make any other changes. Thanks!

**Comment by faustbrian** [comment]
Looks good, will put it on packagist in a few hours. Thanks!

**Pull request merged**
