### PR TITLE
Typo in ALL providers

### PR DESCRIPTION
**Pull request by Max13**
I saw this typo in every providers README.

The driver is called this way: `Socialite::with('provider')` while [`with`](https://laravel.com/docs/socialite#optional-parameters) serves another purpose.

The correct way to call Socialite driver is: `Socialite::driver('provider')`

### CODE REVIEW

**Comment by Max13** [comment]
I'm on it

**Comment by Max13** [comment]
@atymic Did I already PR'd a change for the docgen template or am I missing the concerned file?

**Comment by atymic** [comment]
> @atymic Did I already PR'd a change for the docgen template or am I missing the concerned file?

`tools/docgen.php` :)

**Comment by Max13** [comment]
Here you are ee881c2

**Pull request merged**
