### PR TITLE
Added Wonderlist oauth2 provider

### PR DESCRIPTION
**Pull request by andrewmherren**

### CODE REVIEW

**Comment by m1guelpf** [comment]
Needs a PR to the docs repo

**Comment by andrewmherren** [comment]
@m1guelpf can you point me to any documentation about the PR to the docs repo? I can't find reference anywhere regarding what needs to be done for that. I found the docs repo itself but even  Documentation/docs/contribute.md only mentions creating providers and submitting PRs to this repo so i'm a little lost.

Any pointers would be very much appreciated. Thanks

**Comment by musamamasood** [comment]
@andrewmherren let me try to help with docs repo.

**Comment by andrewmherren** [comment]
@musamamasood Thanks! I appreciate any help you can give!

**Pull request merged**
