### PR TITLE
new Provider projectv

### PR DESCRIPTION
**Pull request by vreezy**
new Provider projectv

### CODE REVIEW

**Comment by vreezy** [comment]
Projectv can be found at https://v.enl.one/login

**Comment by faustbrian** [comment]
Will merge this tomorrow.

**Comment by faustbrian** [comment]
@vreezy Please also add the Provider to https://github.com/SocialiteProviders/Providers/blob/master/build/split.sh

**Comment by vreezy** [comment]
@faustbrian done

**Comment by faustbrian** [comment]
Please remove the `.idea/vcs.xml` file.

**Comment by vreezy** [comment]
ok i hope now its fine... sry iam new to git ant its my fisrt fork.

**Comment by faustbrian** [comment]
I will merge it and fix the things that are still wrong. Provider should be available tomorrow.

**Pull request merged**
