### PR TITLE
Fix AppleProvider throw InvalidStateException

### PR DESCRIPTION
**Pull request by damonto**
At previous PR I only tested the stateless mode. The stateful mode will throw `InvalidStateException` I have fixed this issue on  This PR.

### CODE REVIEW

**Comment by atymic** [comment]
Is this ready to go @damonto ?

**Comment by damonto** [comment]
@atymic Yes.  I  tested it. its works well

**Comment by atymic** [comment]
Could you resolve the conflict then i'll merge. Thanks

**Comment by damonto** [comment]
Done.

**Review by atymic — APPROVED** [review]

**Pull request merged**
