### PR TITLE
Added WS02 Identity Provider

### PR DESCRIPTION
**Pull request by CodyPChristian**

### CODE REVIEW

**Comment by m1guelpf** [comment]
Could you maybe rename the provider to something more... unique?
Also please add it to the splits script & PR it to the docs repo.

**Comment by CodyPChristian** [comment]
Hey, I can however what I named this is the real name of the service.

**Comment by m1guelpf** [comment]
Maybe include WSO2 in the name or something?

**Comment by atymic** [comment]
@CodyPChristian 

Please PR to the docs repo :)

**Comment by atymic** [comment]
@CodyPChristian docs are still needed.

**Comment by antonkomarev** [comment]
I'd still prefer to have WSO2 prefix, because IDENTITY is just a part of the name:
WSO2 Identity Server

**Comment by atymic** [comment]
Closing due to inactivity. Ping me if you'd like to continue the PR :)

**Pull request closed without merging**
