### PR TITLE
SURFconext: Change URLs and keys to reflect changes done by SURF

### PR DESCRIPTION
**Pull request by ArlonAntonius**
Tried using this SocialiteProvider earlier today and it was not working. Decided to do some digging, temporarily add some code in our project to make it work. Everything is working now so decided to create a PR to get this changed structurally.

A few keynotes:
- SURF changed their endpoints and usage of old endpoints would lead to [a redirect to their docs regarding the migration](https://wiki.surfnet.nl/display/surfconextdev/OpenID+Connect+Migratie).
- Decided to document the optional test key as it was hidden now.

### CODE REVIEW

**Review by atymic — APPROVED** [review]
Awesome, thanks for the PR :D

**Comment by ArlonAntonius** [comment]
Damn you were quick @atymic, thanks for merging so quickly.

Any idea on when you will tag a new release so we can use this? 🤔

**Comment by atymic** [comment]
Will do now, was cooking 👍

**Comment by atymic** [comment]
https://github.com/SocialiteProviders/SURFconext/releases/tag/4.1.0

**Comment by ArlonAntonius** [comment]
Thank you, you're awesome! 😄

**Pull request merged**
