### PR TITLE
Added OSChina oAuth2 Provider 

### PR DESCRIPTION
**Pull request by dingdayu**
I follow the [contribute documentation](https://socialiteproviders.netlify.com/contribute.html).

Generate code templates from the [generator](https://github.com/SocialiteProviders/Generators).

But it is different from other Providers: Such as `src` directory.

Should I share code through a separate project? 

Just like: [Weixin](https://github.com/SocialiteProviders/Weixin)

### CODE REVIEW

**Comment by m1guelpf** [comment]
Please add to split script and documentation

**Comment by dingdayu** [comment]
Done

**Comment by dingdayu** [comment]
@m1guelpf The composer package was not created

**Comment by dingdayu** [comment]
@m1guelpf Ok, please as soon as possible.

**Pull request merged**
