### PR TITLE
add Laravel Passport Provider

### PR DESCRIPTION
**Pull request by recca0120**

### CODE REVIEW

**Comment by faustbrian** [comment]
New Providers for this repository should only contain the composer.json, *ExtendSocialite.php, Provider.php and Server.php if needed.

**Comment by recca0120** [comment]
update ..

**Comment by faustbrian** [comment]
`"SocialiteProviders\\LaravelPassport\\": "src/"` should be `"SocialiteProviders\\LaravelPassport\\": ""`

**Comment by recca0120** [comment]
done.

**Comment by faustbrian** [comment]
Will move it to its repository later today.

**Pull request merged**
