### PR TITLE
Fix pinterest provider

### PR DESCRIPTION
**Pull request by AstroCorp**

### CODE REVIEW

**Comment by atymic** [comment]
Can you clarify what this fixes?

**Comment by AstroCorp** [comment]
This:
`$user = Socialite::driver('pinterest')->user();`

Show this error:
`Client error: POST https://api.pinterest.com/v5/oauth/token resulted in a 400 Bad Request response: {"code":1,"message":"Invalid request body"}`

I asked pinterest what was going on and this is their response:
Screenshot_20220926_114821

**Comment by jsainton-godaddy** [comment]
FWIW, I think a lighter touch approach here would be to simply add the following code to the Provider:
```
    protected function getTokenHeaders($code)
    {
        return [
            'Authorization' => 'Basic '.base64_encode($this->clientId.':'.$this->clientSecret),
            'Content-Type' => 'application/x-www-form-urlencoded',
        ];
    }
```
Confirmed locally that this approach works fine, without removing any other values.

**Comment by atymic** [comment]
@jsainton-godaddy could you  PR that please?

**Comment by AstroCorp** [comment]
@atymic ready.

**Review by atymic — APPROVED** [review]

**Pull request merged**
