### PR TITLE
fix Kakao user properties

### PR DESCRIPTION
**Pull request by kimbeejay**

### CODE REVIEW

**Comment by faustbrian** [comment]
Why would you move the nickname to the name instead of the nickname field like it is currently?

**Comment by kimbeejay** [comment]
Actually Kakao does not have real name field and uses nickname instead of it

**Comment by faustbrian** [comment]
Then the nickname should be used for name and nickname because this will otherwise be a breaking change.

**Comment by kimbeejay** [comment]
Hm.. indeed. I'll fix this

**Pull request merged**
