### PR TITLE
feat: re implement steam provider

### LINKED ISSUE #383: Replace LightOpenID for Steam provider
The [Steam provider](https://github.com/SocialiteProviders/Steam) depends on [LightOpenID](https://github.com/iignatov/lightopenid), which is [abandoned](https://github.com/iignatov/LightOpenID/issues/9#issuecomment-186659836). It is currently incompatible with PHP 7.4 and has pull requests open since 2016.

Error Exception on callback:
```
Function get_magic_quotes_gpc() is deprecated
```

From `iignatov\lightopenid\openid.php:891`:
```
$params['openid.' . $item] = function_exists('get_magic_quotes_gpc') && get_magic_quotes_gpc() ? stripslashes($value) : $value;
```

### PR DESCRIPTION
**Pull request by atymic**
WIP. Need to test. Anyone using this who's got a app setup, would be awesome if you could help with testing :)

New version drops all dependencies :) 

Closes #383

### CODE REVIEW

**Comment by Metrakit** [comment]
@atymic Its works. I'm currently using your fix in production because i have no choice and yeah its work perfectly

**Comment by atymic** [comment]
I'll clean in up and merge it today or tomorrow :)

**Comment by atymic** [comment]
Tagged new version :D 
https://github.com/SocialiteProviders/Steam/releases/tag/v3.0.0

**Comment by Metrakit** [comment]
Thanks @atymic

**Pull request merged**
