### PR TITLE
Lint the PHP code

### PR DESCRIPTION
**Pull request by lucasmichot**
Lint the PHP code for all the versions of PHP

This is very required as we have no tests running for this repository.

### CODE REVIEW

**Comment by atymic** [comment]
We have styleci running, what's the reason for this sorry?

**Comment by lucasmichot** [comment]
> We have styleci running, what's the reason for this sorry?

StyleCI is only checking for the code style - and reports errors. The service runs on PHP8.
It uses php-cs-fixer (+ custom) rules to ensure that all versions of recent PHP versions can be covered.

But at no time is code linting executed.
if we were to run tests for PHP versions, those errors in the code would break the execution.
Linting the code is a fast way to detect them.

**Comment by atymic** [comment]
Can you resolve the issues please :)

**Review by atymic — CHANGES_REQUESTED** [review]
Fix conflicts

**Comment by lucasmichot** [comment]
> Fix conflicts

Done @atymic

**Review by atymic — APPROVED** [review]

**Pull request merged**
