### PR TITLE
Add Pipedrive provider

### PR DESCRIPTION
**Pull request by daniti**

### CODE REVIEW

**Comment by faustbrian** [comment]
Has to be added to https://github.com/SocialiteProviders/Providers/blob/master/build/split.sh and please remove the .DS_Store file

**Comment by daniti** [comment]
Pipedrive added to split.sh and .DS_Store removed. Please check again...

**Comment by faustbrian** [comment]
Will move it to its own repository tomorrow and put it on packagist.

**Comment by daniti** [comment]
Manager dependency for ~3.0 needs to be added. Will make a new PR

**Pull request merged**
