### PR TITLE
Normalize the case of the identifiers names

### PR DESCRIPTION
**Pull request by lucasmichot**
This PR normalizes the case of the identifiers names

### CODE REVIEW

**Comment by atymic** [comment]
@lucasmichot is this going to need a new release?

**Comment by lucasmichot** [comment]
Ye

> @lucasmichot is this going to need a new release?

Yes @atymic

**Comment by lucasmichot** [comment]
> Sorry, I mean will it be a breaking change? @lucasmichot

Yes it does

**Comment by atymic** [comment]
> > Sorry, I mean will it be a breaking change? @lucasmichot
> 
> Yes it does

Do we need to add update notes for existing apps, then?

**Comment by lucasmichot** [comment]
No we don't, the identifier is anyway used as lowercase in the `\SocialiteProviders\Manager\Helpers\ConfigRetriever`

**Comment by atymic** [comment]
> ConfigRetriever

Looks like this pulls from the `extendSocialite` method, not the identifier one. So this is fine.

**Pull request merged**
