### PR TITLE
add OAuth Ufutx Provider

### PR DESCRIPTION
**Pull request by glore**
change  to social  namespace

### CODE REVIEW

**Comment by faustbrian** [comment]
The INSTALL, README and LICENSE have to go as providers themselves don't contain them.

**Comment by glore** [comment]
@faustbrian  ok, I will remove them.

**Comment by faustbrian** [comment]
Merged, thanks!

**Comment by glore** [comment]
thanks, How can I generate install  document for my Ufutx provide  on http://socialiteproviders.github.io/

**Comment by faustbrian** [comment]
http://socialiteproviders.github.io/providers/ufutx/

**Pull request merged**
