### PR TITLE
Added Nocks Provider

### PR DESCRIPTION
**Pull request by Paulsky**
Please see [https://docs.nocks.com/#oauth-applications](https://docs.nocks.com/#oauth-applications)

### CODE REVIEW

**Comment by Paulsky** [comment]
Sorry @m1guelpf . Please see SocialiteProviders/Documentation/pull/66 .

**Comment by m1guelpf** [comment]
@Paulsky Please solve merge conflicts so this can be pulled in 😄

**Comment by Paulsky** [comment]
Alright, I have updated my fork and fixed the merge conflict. I have also added Zeit in the build script. How is this @m1guelpf ? 🙂

**Comment by atymic** [comment]
Please rebase the PR :)
You are adding files that were previously removed.

**Comment by Paulsky** [comment]
@atymic please check the current version

**Comment by atymic** [comment]
Still see 200+ files changed?

**Pull request closed without merging**
