### PR TITLE
Fix AppleProvider issues #587 #529

### PR DESCRIPTION
**Pull request by damonto**
requires php 7.4 | 8.0

#587

### CODE REVIEW

**Comment by damonto** [comment]
#529  The state code is generated by Str::random(). Maybe we don't need  to use `md5` to encode it.

**Comment by Iamscaredofcode** [comment]
can we merge this @atymic ? or is there something missing?

**Review by m1guelpf — APPROVED** [review]

**Comment by atymic** [comment]
@damonto does this need a new major version of the provider?

**Comment by damonto** [comment]
> @damonto does this need a new major version of the provider?

Yes, This package now requires a higher php version than the old package.

**Comment by atymic** [comment]
Thanks, releasing now 👍

**Comment by damonto** [comment]
@atymic Sorry. I forgot to test usesState,. Can you remove version 5.0? I will create a new request later.

**Comment by atymic** [comment]
https://github.com/SocialiteProviders/Apple/releases/tag/5.0.1

**Pull request merged**
